apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-pv
          persistentVolumeClaim:
            claimName: shared-pv-claim
      containers:
        - name: todo-app
          image: thomasdawson/todo-app:1.13.1
          volumeMounts:
            - name: shared-pv
              mountPath: /app/data
          env:
            - name: PORT
              value: "3000"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
