apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: log-configmap
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: log-writer
          image: thomasdawson/log-writer:1.10
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
        - name: log-reader
          image: thomasdawson/log-reader:2.5
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
            - name: config-volume
              mountPath: /app/config
          env:
            - name: PORT
              value: "3000"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-configmap
                  key: MESSAGE
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
